### ISSUE TITLE
LiDAR simultion in Gazebo

### ISSUE THREAD

**Issue by huckl3b3rry87** [autowarefoundation/autoware_ai#76]
# New Feature
This feature will leverage Gazebo to simulate a LiDAR. With that vehicle dynamics will simulated by Chrono with https://github.com/CPFL/Autoware/issues/1107.

# Status 
With [this commit](https://github.com/huckl3b3rry87/Autoware/commit/b2ca113c3ad926fbd9a412262b022e032bec5994) a HMMWV vehicle is visualized in Gazebo along with an obstacle. By running
```
roslaunch mavs_gazebo move_hmmwv.jl
```
Gazebo pops up and the vehicle moves along the y direction past an obstacle while publishing lidar points as
```
mavs/mavs_gazebo$ rostopic type lidar_points
sensor_msgs/PointCloud2
```
# TODO 
- [x] 1) make make it possible to initialize with other config files for vehicle and obstacle position
- [ ]  2) fix gazebo and RViz views on hmmwv
- [x]  3) fix display issue on the tires
- [x]  4) add speed of obstacles in Gazebo
- [x]  5) add multiple obstacles
- [x]  6) use the robot name parametrically in all files
- [x]  7) add in an option to update the state of the vehicle based off of /state/ parameter
- [ ]  8) add in an option to pause the simulation before it starts 	
- [ ] 9) add in an option to convert the format of the data to PointCloud
- [ ] 10) add in an option to not simulate Gazebo
- [ ] 11) add in an option to pass the reference frame of the vehicle and the lidar
